### PR TITLE
added a method to scale by x or y axis

### PR DESCRIPTION
**Pull request by CoderNamedHendrick**

### CODE REVIEW

**Comment by CoderNamedHendrick** [comment]
@letsar  I noticed there was no method to scale by x or y. I am currently experimenting with this package and the need arose so I thought to contribute that. Is my PR alright or could it be better implemented.

**Comment by CoderNamedHendrick** [comment]
@letsar

**Comment by letsar** [comment]
Hi @CoderNamedHendrick!
Thanks for your PR but I think I will find another way to create a non uniform scale effect, because I would prefer having only one method for scaling.
I think I will remove the `scale` parameter and use `x`,`y`,`z` parameters instead, for more flexibility. It will be a breaking change though.

**Comment by CoderNamedHendrick** [comment]
> Hi @CoderNamedHendrick!
> Thanks for your PR but I think I will find another way to create a non uniform scale effect, because I would prefer having only one method for scaling.
> I think I will remove the `scale` parameter and use `x`,`y`,`z` parameters instead, for more flexibility. It will be a breaking change though.

I was going to do that so it matches the Transform.scale parameters but wanted to get your feedback on it. I can fix my pr to do that instead if you don't mind

**Comment by letsar** [comment]
Oh I took the liberty to do it myself since it was not a lot of work, I hope you don't mind.
I've just published a 0.0.4 version of this package with these parameters.
I will close this PR since it's the code is there now.
Thanks again for your PR and don't hesitate to share your feedbacks ;-)

**Pull request closed without merging**
